"""Added bill.votes column

Revision ID: 20260813_bill_vote_column
Revises: 20260813_vote_review_audit
Create Date: 2026-08-13 20:19:24.479841

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20260813_bill_vote_column"
down_revision: Union[str, Sequence[str], None] = "20260813_vote_review_audit"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bills",
        sa.Column("votes", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bills", "votes")
    # ### end Alembic commands ###
