"""baseline

Revision ID: 595916aec37b
Revises:
Create Date: 2026-08-04 17:15:56.876858

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "595916aec37b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
