"""Added file_size and page_num to raw_motion_documents

Revision ID: 5cd01ffba69d
Revises: d7f1722121a4
Create Date: 2026-08-04 17:51:44.591729

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5cd01ffba69d"
down_revision: Union[str, Sequence[str], None] = "d7f1722121a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "raw_motion_documents", sa.Column("file_size", sa.Float(), nullable=True)
    )
    op.add_column(
        "raw_motion_documents", sa.Column("num_pages", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raw_motion_documents", "num_pages")
    op.drop_column("raw_motion_documents", "file_size")
    # ### end Alembic commands ###
