name: GitFlow PR Rules

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  validate-gitflow:
    runs-on: ubuntu-latest

    steps:
      - name: Validate PR source and target branches
        env:
          HEAD_REF: ${{ github.head_ref }}
          BASE_REF: ${{ github.base_ref }}
        run: |
          echo "Source branch: $HEAD_REF"
          echo "Target branch: $BASE_REF"

          is_feature=false
          is_release=false
          is_hotfix=false
          is_dev=false

          if [[ "$HEAD_REF" =~ ^dev ]]; then
            is_dev=true
          fi

          if [[ "$HEAD_REF" =~ ^feature/[a-z0-9._-]+$ ]]; then
            is_feature=true
          fi

          if [[ "$HEAD_REF" =~ ^release/(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$ ]]; then
            is_release=true
          fi

          if [[ "$HEAD_REF" =~ ^hotfix/[a-z0-9._-]+$ ]]; then
            is_hotfix=true
          fi

          if [[ "$is_feature" == false && "$is_release" == false && "$is_hotfix" == false  && "$is_dev" == false ]]; then
            echo "Invalid source branch: $HEAD_REF"
            echo "Allowed source branches:"
            echo "  dev"
            echo "  feature/<short-name>"
            echo "  release/<major>.<minor>.<patch>"
            echo "  hotfix/<short-name>"
            exit 1
          fi

          if [[ "$is_dev" == true ]]; then
            [[ "$BASE_REF" == "main" ]] || { echo "dev branch may only target main"; exit 1; }
          fi

          if [[ "$is_feature" == true ]]; then
            [[ "$BASE_REF" == "dev" ]] || { echo "feature/* branches must target dev."; exit 1; }
          fi

          if [[ "$is_release" == true ]]; then
            [[ "$BASE_REF" == "main" || "$BASE_REF" == "dev" ]] || { echo "release/* branches may only target main or dev."; exit 1; }
          fi

          if [[ "$is_hotfix" == true ]]; then
            [[ "$BASE_REF" == "main"  ]] || { echo "hotfix/* branches may only target main or dev."; exit 1; }
          fi
